### ISSUE TITLE
Very weak competitive bidding in B3 of demo boards

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#104]
I would expect a much higher expected value for the double than for pass.
What bad can happen - if partner has neither 4 diamonds nor 4 spades, he will bid 2h and we'll play 2h in a 5-2 or 6-2 fit.

![image](https://github.com/lorserker/ben/assets/33804161/d4519e8d-5ecc-49f4-8ccd-49f49304e39e)

**Comment by ThorvaldAagaard** [comment]
You will have to expand the samples and look how BEN expects the bidding to continue, 

The problem here is that the training recommends pass, so even if X has a higher expected score BEN select the "book-bid" 

The real problem here is training, so I loaded the deal in BBA 
098E4DA4341F63EDF326777799B1
And got this result
![image](https://github.com/lorserker/ben/assets/10560652/82e60453-dc81-4ff5-a84b-e1df4d2f89f5)

So we better report that to BBA

**Comment by ThorvaldAagaard** [comment]
Without the preemptive 3C it is hard to see who should bid more
![image](https://github.com/user-attachments/assets/2cb56551-7bfb-4256-9b77-62765f526fe9)
