### ISSUE TITLE
Pointless double in B155

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#133]
This double to 4h makes no sense at all
![image](https://github.com/lorserker/ben/assets/33804161/e7e541ac-1ed4-4619-b64f-fc5878d60946)

**Comment by ThePokerDude** [comment]
[Event ""]
[Site ""]
[Date ""]
[Board "155"]
[Dealer "S"]
[Vulnerable "None"]
[Deal "S:873.KQ76.KQJ73.Q JT54.A8.A9.T6532 AKQ92.9.865.A987 6.JT5432.T42.KJ4"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "S"]
[Contract "5D"]
[Result "11"]
{PAR of the deal: 5S  = played by North: 450 points}
{PAR computation time: 00'02"}
{Feasability: 7 9 6 11 9 6 2 7 2 3 7 9 6 11 9 6 2 7 2 3 }
[Auction "S"]
1D Pass 1S Pass
2D Pass 4H =1= X
5D Pass Pass Pass
[Note "1: Alert."]
[Play "W"]
HA h9 H5 h6
C3 ca C4 cq
DA d8 D2 dq
C6 c7 CK d3
S5 sq S6 s3
D9 d5 D4 dk
C5 d6 DT dj
H8 s2 H4 hk
C2 c8 H3 hq
ST sk H2 s7
CT c9 CJ d7
S4 s9 HJ s8
SJ sa HT h7

**Comment by ThorvaldAagaard** [comment]
I think this could be due to a bad model, as I have tested in BBA, and that looks ok: https://github.com/EdwardPiwowar/BBA/issues/366

With the current model for GIB, this is the result
![image](https://github.com/lorserker/ben/assets/10560652/0315bc1d-586c-4c12-b655-98a46ef7a655)

But with the latest SAYC-model for UCBC it looks like this
![image](https://github.com/lorserker/ben/assets/10560652/e0b7b087-8394-4c29-b033-3e967ee4fb3e)

But in fact we are here letting BEN play the WBridge5-sayc, so I rotated the deal and got this
![image](https://github.com/lorserker/ben/assets/10560652/a6541284-dd89-42be-a123-a17820483a8a)

So in the SAYC model X is a possible bid and naturally it gives a good score.

As it is a leaddirecting double we could add some quality constraints on the hand, but looking at the samples we can see, atht the problem is that BEN expects 4HC could be the final contract
![image](https://github.com/lorserker/ben/assets/10560652/c37d8333-3936-4fd6-92f5-e568fa761aac)

and it sees 4H as natural and not the splinter it really is, so this seems to be a question of proper training.

We need a set of lead directing doubles included in the training.

**Comment by ThorvaldAagaard** [comment]
https://github.com/EdwardPiwowar/BBA/issues/367

**Comment by ThorvaldAagaard** [comment]
Latest model
![image](https://github.com/user-attachments/assets/5b0964fa-5976-4dca-8f9b-c1e2488b4ff2)
