### ISSUE TITLE
Ben misses opportunity for splinter bid

### ISSUE THREAD

**Issue by ThePokerDude** [lorserker/ben#138]
instead of 4s Ben should bid 4h

[Event ""]
[Site ""]
[Date ""]
[Board "172"]
[Dealer "W"]
[Vulnerable "NS"]
[Deal "W:KJ63.J.AK53.AQT2 T.Q96542.JT4.J94 Q982.A83.986.865 A754.KT7.Q72.K73"]
[Scoring ""]
[BCFlags "1f"]
[Generator "BridgeComposer Version 5.104.1"]
[South "WBridge5"]
[West "ben0308p5dd"]
[North "WBridge5"]
[East "ben0308p5dd"]
[Declarer "E"]
[Contract "4S"]
[Result "10"]
{PAR of the deal: 4S  = played by East : 420 points}
{PAR computation time: 00'03"}
{Feasability: 4 4 8 3 4 9 9 5 10 8 4 4 8 3 4 9 9 5 10 8 }
[Auction "W"]
1D Pass 1S Pass
4S Pass Pass Pass
[Play "S"]
sa SK st S2
s4 S6 h6 S8
d2 DA d4 D8
h7 HJ h2 HA
ht S3 h4 H8
d7 DK dt D6
dq D5 dj D9
c3 CQ c4 C6
s5 SJ h5 SQ
s7 C2 h9 S9
c7 CA c9 C5
hk D3 cj H3
ck CT hq C8

![image](https://github.com/lorserker/ben/assets/33804161/fd4c7491-72fc-49e7-87d6-a109d6881352)

**Comment by ThorvaldAagaard** [comment]
The neural network agree
![image](https://github.com/lorserker/ben/assets/10560652/8f9e9961-60e4-4f9a-a83c-dab9c4331c26)
but simulation doesn't

The better the net, the more we should trust the net, but it is still to difficult to decide when - because a high score can be because we have few examples or because it is the right bid.

I won't do anything by this for now.

**Comment by ThorvaldAagaard** [comment]
Closing as this is OK now
![image](https://github.com/user-attachments/assets/d893723b-4b18-4f27-8566-c23357111fae)
Latest BEN
![image](https://github.com/user-attachments/assets/67cab2ea-bf8d-4de4-a97d-16d437c1583e)
