### ISSUE TITLE
Question on Robot Lead Selection

### ISSUE THREAD

**Issue by adajcw** [lorserker/ben#30]
Confused as to why a club was the selected lead here when a diamond had a lower %   (DA, DK, Dx and a ruff get you to an empirical 44% MatchPoint of field where the ruff disappears with a club lead and a resulting MatchPoint result  of 7%)

![Screen Shot 2022-11-01 at 1 11 09 PM](https://user-images.githubusercontent.com/9043241/199307541-ad75f89f-c092-4273-866f-0d0ab2e9894c.png)

**Comment by lorserker** [comment]
hi, i agree that the DA is the better lead.
also the number of tricks estimated for declarer is lowest on the DA lead (10.072)

so this is either a bug or some strange computer logic, and i am thinking what the computer's logic might be:

AK and a ruff is only 3 tricks. i think it tries to set the contract somehow, and for that it needs another trick from partner. i guess it tries to find this trick first (could be the A of clubs) so partner can play diamond through declarer's Qxx.
AK and a diamond can be a risk if declarer (over)ruffs the 3rd round because a possible long jack could be established in dummy on which to discard the singleton club from hand.

of course the above logic is a bit strange and computer-like. the normal play is to start with the A, see dummy and what partner signals, and then decide what to do, there is still time to switch.
but the computer thinks in its own way :)

**Comment by ThorvaldAagaard** [comment]
I think the problem here is that the decision isn't made based on the numbers you see on the screen,

I just had this example:

![image](https://github.com/lorserker/ben/assets/10560652/cccf34f4-28db-4069-93a0-6036d626b010)

Based on this it should select a small heart as lead (Probably like most of us) but BEN started with a small club.

Now looking at the log from the gameserver I noticed this calculation
![image](https://github.com/lorserker/ben/assets/10560652/910e6bb9-8ffc-4828-9b6f-cae1933eb8f4)

Now, when playing teams it might be right to make the lead that gives declarer the least chance to make the contract, but at matchpoints it might be more right to make the lead with chance of most tricks.

In the lead function it is selecting the card with the lowest chance of making the contract:
![image](https://github.com/lorserker/ben/assets/10560652/1d8ec0eb-edd1-4718-b5ef-5052ef75d2fe)


In my example where the contract is doubled it should be clear that neither of the two calculations should be used, but instead make the lead that will - on average - give the highest score, 

So when playing 1NX instead of finding out if it 5,6,7,8  or more you should look at the scores -280, -180, 100, 300, 500+
This is not only when doubled, but it is clearer to see the difference

I am not sure if that was the intention with ```insta_score```, that seems 0 always.

I just checked the code, and it seems ```insta_score``` is comming from this code:
![image](https://github.com/lorserker/ben/assets/10560652/534fcf39-b8e3-46a2-80ed-5d9a2c3e0807)

where it is always reset to 0 for candidates. Perhaps Lorand can explain why.

**Comment by ThorvaldAagaard** [comment]
Adding this in ```src/frontend/viz.js```

![image](https://github.com/lorserker/ben/assets/10560652/3e49bdd9-b1b5-4491-96a1-8dee4932c274)

and you can see the chance for making the contract

**Comment by ThorvaldAagaard** [comment]
I just remembered Lorand told me, that he uses a neural network if there are multiple possible leads with the same value, and I can see that ```insta_score``` is from that neural network.

Looking at the code a possible lead will be discarded if the score from the neural network is less than 0.05, so that is why we only see 4 possible leads.

**Comment by ThorvaldAagaard** [comment]
As it is explained why BEN selected  C2 as lead I am going to close this issue.
