### ISSUE TITLE
Suspicious switch defending 3NT

### ISSUE THREAD

**Issue by lorserker** [lorserker/ben#38]
S None
W:KT43.T6.2.AJ9642 962.73.AKQ83.T83 AJ7.AK982.T6.Q73 Q85.QJ54.J9754.K
P P P 1H P 1S P 1N P 2C P 3S P 3N P P P

South leads a diamond, North wins the queen and switches?!!

**Comment by ThorvaldAagaard** [comment]
I have just tested this by setting a human West and South. 

The lead against 3N is a diamond, but the continuation is different based on the diamond selected, as after the lead of the 9, North did only play Q followed K, and then a heart - and I am not sure, but it could even be dependent of the next card played.

In my test any smaller diamond and North will continue diamonds. 

It is also interesting that the sample hands, when I lead the 9 followed by the 5 was

![image](https://github.com/lorserker/ben/assets/10560652/5f2a3271-96ba-4bc8-b93b-6cc3eccdfeb0)

Showing at least 3 diamonds in souths hand.

When leading a small diamond all samples has at least 4 diamonds.

I think this is a problem with the sample hands

**Comment by ThorvaldAagaard** [comment]
In all your samples (we can see) partner has KT of diamonds, so it will go down, whatever card is played. Also consistent with the number of tricks, that is 2 in both situations.

So there is probably 2 problems. Why is DT assumed in south, and looking at the score from the neural network, it should probably select the highest iscore, when tricks and score are equal.

I tried to recreate the board, and found some interesting observations.

1: West did bid 3N
2: I lead a club, and now there is 9 tricks for EW, but look what happened at trick 9

![image](https://github.com/lorserker/ben/assets/10560652/89dee355-a63b-452f-b4e5-80beed181d2c)

instead of playing H5 as the ninth trick it played DJ. An obvious error.

And this time the highest score from nn was selected.

How did the play go when you played it?

**Comment by eamongalligan62** [comment]
![image](https://github.com/lorserker/ben/assets/124155928/ab719511-035a-4acd-bb46-d6b6ec863ad9)

Same 2NT hand as above but sample puts AK of spades in South all the time so spade to queen is same result as cashing 2 winning hearts .....but a human won't do this or a GIB or a Wbridge5

**Comment by eamongalligan62** [comment]
PLay was club lead and 4 rounds of clubs and 3 rounds of hearts .. and then with 2 known Heart winners ..it plays towards spade queen as sample says this is good

**Comment by ThorvaldAagaard** [comment]
I am not sure we see all the samples, but I will have a look at the code and generation of samples tomorrow

**Comment by eamongalligan62** [comment]
In bots.py there are 3 places with sample numbers ....first one at line 56 where 10 is the sample number 
Then line 249 gives us samples which seem to be opening lead of 100 
The line 520 gives us 20 samples 

I am aware that Lorand changed the sampling recently to summing the samples until he reaches 90% or something like that 
whereas before is was minmum of a number given above or samples generated 

I find the new sampling method did not help so much in any matches I played ... I even played one against the other with same  bidding files and binfo file 

I built my NN with 2.5 million hands and 4.5 million iterations ... my binfo file is 1.5 million iterations 

I can beat most 1 million iteration bens but no chance against even level 3 Wbridge5 where we lose by about 1.5 imps a board. 

However I think something is wrong with sampling ....and is it possible to cash winners in human terms 100% line  instead of using samples which might not be 100% line 

eamongalligan62@gmail.com

**Comment by ThorvaldAagaard** [comment]
At line 56 we are in the bidding, and there is typical generated up to 64 hands, but only the first 10 are written to the log

At line 249 we are looking at the opening lead. Here we will display up to 100 hands, but normally around 20-30 boards that match the bidding is shown. - looking a bit deeper on this it creates 4096 hands and test if they match the bidding. If less than 20 boards are matching of the 4096 hands the trust in the neural network bidding is lowered.

At line 520 we are looking at playing and generating 100 hands, some of the hands are discarded as they do not match the bidding, but again only up to 20 samples are written to the log.

**Comment by ThorvaldAagaard** [comment]
I have checked and as far as I can see there is generated 100 boards matching the actual bidding (or more correct it generates 40 * 100, but stops when there is found 100 matching hands) - during the play boards no longer matching the actual play is eliminated, so after 2 heart-tricks, and 4 clubs, the situation, when cashing the 5th club is that only these 37 boards of the original 100 is left
![image](https://github.com/lorserker/ben/assets/10560652/cd9b3f0a-6ae5-4226-8a4b-d595fc12b544)

Now look at the 37 boards, and notice that on only 2 boards South doesn't have AK of spades, and in both situations it is with a doubleton heart. So after the last club and heart ace after 8 tricks and dummy on the lead these samples remain

![image](https://github.com/lorserker/ben/assets/10560652/cf89b872-8f8d-476d-9568-6bcdb9c316f6)

So I agree that there is problem with the sampling. One idea might to resample the hands after each trick, but that might be to timeconsuming, so perhaps it should be done after 7 tricks (or configurable)

Another idea is to drop samples as soon as the combinations for the remaining cards is below some threshold. I real bridge I have told my partners, that when before playing the last 3 tricks you should as defender or declarer normally know the entire hand. With 3 cards remaining there are only 20 possible combinations, before looking at bidding, voids, discards etc

**Comment by ThorvaldAagaard** [comment]
I have now looked mode at how the samples are generated, and I think the problem is that the robot "validates" each hand by checking the opening lead from that specific hand, and discards the hand if it would have lead another card from that hand (Based on statistics).

If I change ```lead_accept_threshold``` to a lower value (0.01) we would not have only 8 boards in the above situation, but 79 boards, and the candidates at trick 9 would have these values
![image](https://github.com/lorserker/ben/assets/10560652/2c0498fc-0b0b-462c-9896-c8bf735cf6c5)

I think in general we should not drop samples based on the lead, as we can't trust opponents to follow the same rules for opening leads as BEN.

If opening lead should be used I think it is a better idea to sort the samples based on the score for the opening lead and then select the 100 with the highest score.

**Comment by lorserker** [comment]
@ThorvaldAagaard thanks for the detailed analysis.
yes, I agree with your conclusions that rejecting samples based on leads or cards played is not good. reweighting or sorting samples as you suggested seems a better idea

**Comment by ThorvaldAagaard** [comment]
I have tried to recreate the initial problem, but with the default bidding model we get this bidding:
![image](https://github.com/lorserker/ben/assets/10560652/471df211-92b9-44b8-b58b-2cc81f34c0a3)

So a much better contract and the defensive problem not there.
